---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskTracker_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true